### PR TITLE
Massive changes to UX/UI

### PR DESCRIPTION
**Pull request by aniketnk**
## Screenshots:
   [Screenshot 1](https://imgur.com/xpTBgsw)
   [Screenshot 2](https://imgur.com/gVQs3pc)

Check it out and let me know how it looks!

### CODE REVIEW

**Comment by parthvshah** [comment]
It looks really bad.

**Comment by aniketnk** [comment]
@parthvshah The background or the colors?

**Comment by parthvshah** [comment]
The background image is fine. We can look for other background images later. Check out the Verge wallpapers. Some of them are quite cool. The main issue is the colour behind the text. Wherever there is text, let there be plain white background there.

**Comment by aniketnk** [comment]
The Verge has great wallpapers, but the image size is massive. Mine is a small 10kb image which keeps repeating to fill the screen.
You can mess around with different colors and tell me which looks the best. I used [Adobe Color CC](https://color.adobe.com/explore/?filter=most-popular&time=month) to pick colors that go together.
Check out `client\app\styles\styles.scss` for color variables. `dark` is for navbar background and buttons. `white` is the default background color and text color for anything on `dark`. `light` is the background color for cards, jumbotron, etc.

You can disable the body background by commenting line in `client\public\index.html`.

**Comment by RRK1000** [comment]
The colors are really off. The text looses it's readability if the background color isn't white. Also, does a background image? The solid white color complimented the website's purpose, I feel.

**Pull request merged**
